# El método de k-means

In [1]:
import numpy as np

In [2]:
data = np.random.random(90).reshape(30,3)
data

array([[0.41505246, 0.69568281, 0.85916982],
       [0.94118914, 0.67326072, 0.98883003],
       [0.05686858, 0.21693112, 0.23831007],
       [0.46301287, 0.58520837, 0.80656563],
       [0.52966822, 0.04041169, 0.23888831],
       [0.87276717, 0.20005652, 0.98509997],
       [0.6833192 , 0.78384328, 0.63036123],
       [0.254006  , 0.2123997 , 0.65313105],
       [0.5078382 , 0.29551305, 0.17972665],
       [0.2749047 , 0.02368147, 0.2215364 ],
       [0.12980423, 0.11162321, 0.47784785],
       [0.30623856, 0.767395  , 0.61053507],
       [0.58759818, 0.86572175, 0.44347183],
       [0.33280877, 0.08611415, 0.99886629],
       [0.21562632, 0.6580484 , 0.94736633],
       [0.16271179, 0.11367358, 0.01743521],
       [0.36005437, 0.77427934, 0.60686919],
       [0.33737506, 0.09231906, 0.54521685],
       [0.7478034 , 0.14655933, 0.43668723],
       [0.55247327, 0.00586974, 0.02414921],
       [0.93923027, 0.10899699, 0.91960588],
       [0.03294405, 0.12966345, 0.12046792],
       [0.

In [4]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.55247327, 0.00586974, 0.02414921],
       [0.7478034 , 0.14655933, 0.43668723]])

In [5]:
from scipy.cluster.vq import vq

In [6]:
vq(data, clust_centers)

(array([1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
        1, 1, 1, 1, 1, 1, 1, 1]),
 array([0.76860349, 0.78719379, 0.57968594, 0.64056901, 0.21869179,
        0.56500834, 0.6691776 , 0.54315629, 0.33179795, 0.34106197,
        0.62035289, 0.78143427, 0.73682178, 0.70136971, 0.89756707,
        0.40445118, 0.75719457, 0.42798611, 0.        , 0.        ,
        0.52083163, 0.54269033, 0.80013508, 0.73232471, 0.5745112 ,
        0.35681161, 0.46702732, 0.73249572, 0.56178269, 0.90699494]))

In [7]:
from scipy.cluster.vq import kmeans

In [8]:
kmeans(data, clust_centers)

(array([[0.33323915, 0.11762457, 0.25002657],
        [0.49795904, 0.53890874, 0.7387388 ]]), 0.34808697913285797)

In [9]:
kmeans(data, 2)

(array([[0.51079867, 0.55609342, 0.74324447],
        [0.32603614, 0.12624049, 0.28667243]]), 0.34714420593579415)

In [10]:
from sklearn.cluster import DBSCAN